### ISSUE TITLE
Odd block issue when creating the actual blocks while loading from a save

### ISSUE THREAD

**Issue by Althoumb** [ihs-programming/Dirtbox#19]
When I try to convert a string to the block in the following code (lines 36-43 in Saver.java):

```
private Block stringToBlock(String blockstring) {
	String[] stringarray = blockstring.split(" ");
	BlockType blocktype = BlockType
			.valueOf(stringarray[0]);
	float xpos = Float.parseFloat(stringarray[1]);
	float ypos = Float.parseFloat(stringarray[2]);
	return Block.createBlock(blocktype, xpos, ypos);
}
```
there is a peculiar issue. 

When the block is created with `Block.createBlock(blocktype, xpos, ypos);` it's not actually the same block as the original created while saving. The position is the same, and the blocktype is the same, but the sprite is not the same. This can be seen through the debugging output created after using the "!load" command after using "!save":
![image](https://user-images.githubusercontent.com/33137947/36338762-64270f2e-136c-11e8-9831-5d6e4385f0c2.png)

I checked the code for the createBlock() and Block() method in Block.java, but could not find anything wrong which would cause this issue. Someone please look into this odd issue, I can't figure it out and it's driving me nuts. I know one of you will find the issue within five minutes.

**Comment by Peachball** [comment]
I'm not sure if this is a problem. The objects are different, but that's because every block has it's own sprite. If a new block is created, a new sprite object will also be created. Are there any differences in the appearance of the sprite as a result of this difference?

Additionally, I would consider storing the block positions as integers instead of floats.

**Comment by Althoumb** [comment]
If you do !save then !load, the whole world disappears except for a couple blocks with weird all-black sprites which break instantly, adding stone to the inventory.

The reason block positions are floats is that they are a Point, which is in the form (float, float).

**Comment by Althoumb** [comment]
Closed, not actually the issue occuring

**Comment by Peachball** [comment]
FYI the reason why the problem is happening is that you are using the same currentpoint object (at line 64).

Also, Point objects store points as (int, int). The setLocation method rounds the floats you pass in.
