### ISSUE TITLE
sprites are loaded from sprite sheet offset by one px

### ISSUE THREAD

**Issue by Althoumb** [ihs-programming/Dirtbox#2]

**Comment by Althoumb** [comment]
![image](https://user-images.githubusercontent.com/33137947/34629158-127d328c-f21c-11e7-957d-bcf38acd371b.png)

**Comment by Althoumb** [comment]
![image](https://user-images.githubusercontent.com/33137947/34629192-297f7814-f21c-11e7-8f8e-42ba818dfce2.png)

**Comment by Peachball** [comment]
Sprites have been offset 1px in other direction in [this commit](https://github.com/ihs-programming/Dirtbox/commit/6ff76505acd172555df2a9eb012ea89ec07b18ed)
