### ISSUE TITLE
When loading, the list of visible blocks doesn't actually contain any blocks

### ISSUE THREAD

**Issue by Althoumb** [ihs-programming/Dirtbox#20]
This code right here (288-301 in World.java)
```
	public List<Point> getVisibleBlockLocations(Rectangle view) {
		ArrayList<Point> blockLocs = new ArrayList<>();
		for (int i = (int) (view.getMinX() - 1); i <= view.getMaxX(); i++) {
			Point start = new Point(i, (int) (view.getMinY() - 1));
			Point end = new Point(i, (int) (view.getMaxY() + 1));
			NavigableSet<Point> existingBlocks = getBlocks().navigableKeySet().subSet(
					start,
					true, end, true);
			for (Point p : existingBlocks) {
				blockLocs.add(p);
			}
		}
		return blockLocs;
	}
```

When I try to load from a save, it doesn't mark any of the blocks as visible, so it doesn't draw them or do collisions. It's very odd.

**Comment by Peachball** [comment]
I'm assuming this is related to #19. Currently when you load from a save, `arrayListToBlock(ArrayList<String>)` only adds one block into the resulting treemap. I think `getVisibleBlockLocations` is correct, as the blocks TreeMap is almost empty
