### ISSUE TITLE
##### Command Help Menu Bug

### ISSUE THREAD

**Issue by Althoumb** [ihs-programming/Dirtbox#23]
When an unknown command is submitted, there should be an indicator that the command is not a real command. This does not work if the incorrect command is a prefix of an existing command. As a result:
``` !viewmessage ```
does not create an error message, although the correct command is
``` !viewmessages```

**Comment by Althoumb** [comment]
How do I reproduce this? As shown in the below image, it works fine
![image](https://user-images.githubusercontent.com/33137947/36705981-a48de120-1b1c-11e8-9e8d-3c7dbbf28d1e.png)

**Comment by Peachball** [comment]
My bad, that was on my branch
