### ISSUE TITLE
Lag spikes while drawing blocks

### ISSUE THREAD

**Issue by Althoumb** [ihs-programming/Dirtbox#5]
The following three lines somehow randomly cause up to 1000 ms of lag. This is a big issue, as the game otherwise runs quite smoothly. Please fix!
 "734.582767 ms for draw (!!!) 743.448732 ms for render"

`for (Position p : existingBlocks) {
  				generateRegion.blocks.get(p).draw(vp);
  			}`

**Comment by Peachball** [comment]
Is this only when the viewport is zoomed out?

**Comment by Althoumb** [comment]
No, it happens no matter the zoom.
