### ISSUE TITLE
Character physics break when camera is not locked

### ISSUE THREAD

**Issue by Althoumb** [ihs-programming/Dirtbox#8]
![image](https://user-images.githubusercontent.com/33137947/35239966-d5bdc11a-ff66-11e7-8d80-c217a89a8ad1.png)

^this should be impossible to get to...

**Comment by Peachball** [comment]
I can't reproduce this. What actions did you take in the game?

**Comment by Althoumb** [comment]
Get far away, zoom out so FPS drops, when you recenter camera, Stalin will zip up to the nearest surface

**Comment by Althoumb** [comment]
Closed, no longer able to replicate
